languageCode = "en-us"
title = "myhightech.org"
theme = "papermod"
staticDir = ["static"]
googleAnalytics = "UA-44256981-9"
disqusShortname = "myhightech-blog"

[markup.goldmark.renderer]
unsafe = true

[params]
    ShowShareButtons = true
    ShowReadingTime = true
    comments = true

[params.homeInfoParams]
    Title = "My name is Damian Czaja"
    Content = "A blog about PCs, programming, open source and more"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/trojan295/"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/damian-czaja-01418a104/"
[[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/damczaja"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Categories"
    weight = 2
    url = "/categories/"
[[menu.main]]
    name = "About me"
    weight = 3
    url = "/about/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

