languageCode: "en-us"
title: "myhightech.org"
theme: "papermod"
baseURL: "https://myhightech.org"
staticDir: ["static"]
googleAnalytics: "G-4QTBMDK7P1"
disqusShortname: "myhightech-blog"

outputs:
  home:
    - HTML
    - JSON

params:
  comments: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowPostNavLinks: true

  profileMode:
    enabled: true
    title: "Damian Czaja"
    subtitle: "💻 DevOps Engineer ⛅ Cloud-Native geek"
    imageUrl: "/images/my-face.png"
    imageWidth: 240
    imageHeight: 240

  socialIcons:
    - name: github
      url: https://github.com/trojan295/
    - name: linkedin
      url: https://www.linkedin.com/in/damian-czaja-01418a104/
    - name: toptal
      url: https://www.toptal.com/resume/damian-czaja
    - name: email
      url: mailto://damian.czaja@cloudkon.net
    - name: steam
      url: https://steamcommunity.com/id/trojan295/

menu:
  main:
    - name: Blog
      weight: 1
      url: /posts/
    - name: Categories
      weight: 5
      url: /categories/
    - name: Search
      weight: 8
      url: /search
    - name: About me
      weight: 10
      url: /about/

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "monokai"
    tabWidth: 2
